"""add business entities

Revision ID: 3df6cf4425a1
Revises: 458fba5067cf
Create Date: 2026-08-25 18:56:52.210463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df6cf4425a1'
down_revision: Union[str, Sequence[str], None] = '458fba5067cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'normalized_name', 'entity_type', name='uq_chunk_entity')
    )
    op.create_index(op.f('ix_business_entities_chunk_id'), 'business_entities', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_business_entities_entity_type'), 'business_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_business_entities_normalized_name'), 'business_entities', ['normalized_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_entities_normalized_name'), table_name='business_entities')
    op.drop_index(op.f('ix_business_entities_entity_type'), table_name='business_entities')
    op.drop_index(op.f('ix_business_entities_chunk_id'), table_name='business_entities')
    op.drop_table('business_entities')
    # ### end Alembic commands ###
